### PR TITLE
Add playbooks for deploying a CAPI management cluster only

### PR DESCRIPTION
**Pull request by mkjpryor**
Provides a reference setup for the new Magnum driver.

### CODE REVIEW

**Review by scrungus — COMMENTED** [review]
Looks reasonable, has it been tested at all?

**Comment by mkjpryor** [comment]
Just tested now

**Comment by mkjpryor** [comment]
We should obviously add it to the multinode for SKC at some point

**Comment by mkjpryor** [comment]
The underlying roles will be tested as part of Azimuth CI

**Review by scrungus — APPROVED** [review]
Approved

**Pull request merged**
